apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
      app: api
  name: api
spec:
  replicas: 5
  selector:
      matchLabels:
        app: api
  strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
  template:
      metadata:
        labels:
            app: api
        name: api
      spec:
        containers:
        - image: ghcr.io/<yourgithubaccount>/fabrikam-api:latest 
          env:
            - name: MONGODB_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: cosmosdb
                  key: db              
          livenessProbe:
            httpGet:
                path: /
                port: 3001
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 10
            failureThreshold: 3
          imagePullPolicy: Always
          name: api
          ports:
            - containerPort: 3001
              protocol: TCP
          resources:
            requests:
                cpu: 125m
                memory: 128Mi
          securityContext:
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        imagePullSecrets:
        - name: pullsecret  