apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
      app: init
  name: init
spec:
  replicas: 1
  selector:
      matchLabels:
        app: init
  strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
  template:
      metadata:
        labels:
            app: init
        name: init
      spec:
        containers:
        - image: ghcr.io/renevanosnabrugge/fabrikam-init:latest 
          env:
            - name: MONGODB_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: cosmosdb
                  key: db              
          livenessProbe:
            httpGet:
                path: /
                port: 3000
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 10
            failureThreshold: 3
          imagePullPolicy: Always
          name: init
          ports:
            - containerPort: 3000
              hostPort: 80
              protocol: TCP
          resources:
            requests:
                cpu: 125m
                memory: 128Mi
          securityContext:
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        imagePullSecrets:
        - name: pullsecret  